### PR TITLE
Removed boto3 dependency - Fix #7

### LINKED ISSUE #7: boto3 is unnecessary to import
When dealing with Python Lambda's in AWS... it is unnecessary to import boto3, since that's already a default package imported and provided by the AWS Lambda environment.

### PR DESCRIPTION
**Pull request by infamousjoeg**
Removed boto3 dependency since it is not needed in an AWS Lambda Function.

NOTE:  I did not recompile the `dist` directory files.  This should still be done.

### CODE REVIEW

**Comment by infamousjoeg** [comment]
@nimrody15 @zivshits can I get a couple reviews on this PR?

**Comment by zivshits** [comment]
> @nimrody15 @zivshits can I get a couple reviews on this PR?

Hey Joe,
Currently we don't have an automatic testing environment.
Can you please describe which tests did you perform?

**Comment by infamousjoeg** [comment]
> > @nimrody15 @zivshits can I get a couple reviews on this PR?
> 
> Hey Joe,
> Currently we don't have an automatic testing environment.
> Can you please describe which tests did you perform?

When I deployed this in October 2018, I used my version that didn't include boto3.  Boto3 is provided by AWS' Lambda service by default.

**Comment by yogevh** [comment]
boto 3 is needed now for multi-region, multi account support

**Pull request closed without merging**
